# Copyright SecureKey Technologies Inc.
#
# SPDX-License-Identifier: Apache-2.0

swagger: "2.0"
info:
  version: "1.0.0"
  title: "Gate Keeper"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
basePath: "/v1"
schemes:
  - "https"

paths:
  /protect:
    post:
      tags:
        - "protect"
      summary: "Protect social media handler"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/xml"
      parameters:
        - in: "body"
          name: "body"
          description: "Data to protect and protection policy"
          required: true
          schema:
            $ref: "#/definitions/ProtectReq"
      responses:
        "200":
          description: "Data protected"
          schema:
            $ref: "#/definitions/ProtectResp"


definitions:
  ProtectReq:
    type: "object"
    properties:
      target:
        type: "string"
      policy:
        type: "string"

  ProtectResp:
    type: "object"
    properties:
      did:
        type: "string"

